language: node_js

node_js:
  - "stable"

cache:
  directories:
  - node_modules

script:
  - npm test -- --coverage
  - npm run build
  - npm run minify

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master